apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: graf #create and Write your own namespace 
spec:
  selector: 
    app: grafana
  type: NodePort  
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000